version: '3.5'

services:
  active:
    image: phashboard/active
    volumes:
      #- ./var/sqlite:/var/www/html/var/sqlite
      - static-assets:/var/www/html/public
#    logging:
#      driver: none
    # TODO: disable logging

  nginx:
    image: phashnginxactive
    ports:
      - 80:80
    volumes:
      - static-assets:/var/www/html/public
#    logging:
#      driver: none
# TODO: disable logging

volumes:
  static-assets: ~
